### ISSUE TITLE
İt shows working links as broken. 

### ISSUE THREAD

**Issue by ayyilmaz** [justoverclockl/broken-links-checker#1]
İt shows working links as broken.

**Comment by justoverclockl** [comment]
can you provide an example?

**Comment by ayyilmaz** [comment]
Yes you can try. Also I cant click to links when I disable the exxtension.
https://istihbarat.club/d/588-isinize-yarayabilecek-ilginc-ve-yararli-web-siteleri

**Comment by justoverclockl** [comment]
are these link inside a BBCode? maybe this can be the problem, i will look into this for sure.

**Comment by ayyilmaz** [comment]
Yes inside in BBCode. Like this: `[iStockPhoto](https://www.istockphoto.com/tr) `

**Comment by justoverclockl** [comment]
fixed link checker in the latest version
